version: '3.7'

services:
  # Servicio para la API Go
  apiusuario:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=prueba
    networks:
      - my_network

  # Servicio para MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prueba
    ports:
      - "3306:3306"
    networks:
      - my_network
    volumes:
      - mysql-data:/var/lib/mysql

# Volumen para persistencia de datos de MySQL
volumes:
  mysql-data:

# Definir la red para los contenedores
networks:
  my_network:
    driver: bridge
